# -*- coding: utf-8 -*-
"""hw4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1raNP9Sm6r5cKMpq4M9xHD1M6HSM896QJ
"""

def alignment(input_path, score_path, output_path, aln, gap_open, gap_extend):# Read FASTA
    names, seqs, cur = [], [], []
    with open(input_path) as f:
        for line in f:
            line = line.strip()
            if not line: continue
            if line.startswith(">"):
                if cur:
                    seqs.append("".join(cur))
                    cur = []
                names.append(line[1:].strip())
            else:
                cur.append(line)
    if cur: seqs.append("".join(cur))
    if len(seqs) < 2: return
    n1 = names[0]
    n2 = names[1] if len(names) > 1 else "seq2"
    s1, s2 = seqs[0], seqs[1]

    # Read score matrix
    lines = [l.strip() for l in open(score_path) if l.strip() and not l.lstrip().startswith("#")]
    header = lines[0].split()
    score = {a: {} for a in header}
    for row in lines[1:]:
        parts = row.split()
        r = parts[0]
        for j, val in enumerate(parts[1:]):
            score[r][header[j]] = int(val)
    mode = aln.lower()
    m, n = len(s1), len(s2)
    NEG_INF = -10**9

    # Initialize DP matrices
    M = [[NEG_INF]*(n+1) for _ in range(m+1)]
    X = [[NEG_INF]*(n+1) for _ in range(m+1)]
    Y = [[NEG_INF]*(n+1) for _ in range(m+1)]
    if mode == "global":
        M[0][0] = 0
        for i in range(1, m+1):
            X[i][0] = gap_open + (i-1)*gap_extend
            M[i][0] = NEG_INF
            Y[i][0] = NEG_INF
        for j in range(1, n+1):
            Y[0][j] = gap_open + (j-1)*gap_extend
            M[0][j] = NEG_INF
            X[0][j] = NEG_INF
    else:  # local
        for i in range(m+1):
            M[i][0] = 0; X[i][0] = 0; Y[i][0] = 0
        for j in range(n+1):
            M[0][j] = 0; X[0][j] = 0; Y[0][j] = 0
    best_score = 0
    best_pos = []

    # Fill DP
    for i in range(1, m+1):
        for j in range(1, n+1):
            X[i][j] = max(X[i-1][j] + gap_extend, M[i-1][j] + gap_open)
            Y[i][j] = max(Y[i][j-1] + gap_extend, M[i][j-1] + gap_open)
            diag = M[i-1][j-1]
            if X[i-1][j-1] > diag: diag = X[i-1][j-1]
            if Y[i-1][j-1] > diag: diag = Y[i-1][j-1]
            M[i][j] = diag + score[s1[i-1]][s2[j-1]]
            if mode == "local":
                if M[i][j] < 0: M[i][j] = 0
                if X[i][j] < 0: X[i][j] = 0
                if Y[i][j] < 0: Y[i][j] = 0
                if M[i][j] > best_score:
                    best_score = M[i][j]; best_pos = [(i,j,"M")]
                elif M[i][j] == best_score:
                    best_pos.append((i,j,"M"))
                if X[i][j] > best_score:
                    best_score = X[i][j]; best_pos = [(i,j,"X")]
                elif X[i][j] == best_score:
                    best_pos.append((i,j,"X"))
                if Y[i][j] > best_score:
                    best_score = Y[i][j]; best_pos = [(i,j,"Y")]
                elif Y[i][j] == best_score:
                    best_pos.append((i,j,"Y"))

    # Global: determine final state
    if mode == "global":
        final_score = M[m][n]; state = "M"
        if X[m][n] > final_score: final_score = X[m][n]; state = "X"
        if Y[m][n] > final_score: final_score = Y[m][n]; state = "Y"
        best_score = final_score
        best_pos = [(m,n,state)]
    best_align = ("", "")
    best_len = -1

    # Backtrack for best alignment
    for (i,j,state) in best_pos:
        if mode == "local" and best_score == 0:
            break
        a1, a2 = [], []
        ti, tj, ts = i, j, state
        while True:
            if ts == "M":
                if mode == "local" and M[ti][tj] == 0:
                    break
                a1.append(s1[ti-1]); a2.append(s2[tj-1])
                prev = M[ti][tj] - score[s1[ti-1]][s2[tj-1]]
                if ti > 0 and tj > 0 and M[ti-1][tj-1] == prev:
                    ts = "M"
                elif ti > 0 and tj > 0 and X[ti-1][tj-1] == prev:
                    ts = "X"
                else:
                    ts = "Y"
                ti -= 1; tj -= 1
            elif ts == "X":
                if mode == "local" and X[ti][tj] == 0:
                    break
                a1.append(s1[ti-1]); a2.append("-")
                if ti > 0 and X[ti][tj] == X[ti-1][tj] + gap_extend:
                    ts = "X"
                else:
                    ts = "M"
                ti -= 1
            else:  # ts == "Y"
                if mode == "local" and Y[ti][tj] == 0:
                    break
                a1.append("-"); a2.append(s2[tj-1])
                if tj > 0 and Y[ti][tj] == Y[ti][tj-1] + gap_extend:
                    ts = "Y"
                else:
                    ts = "M"
                tj -= 1
            if mode == "global" and ti == 0 and tj == 0:
                break
        a1.reverse(); a2.reverse()
        aln1 = "".join(a1); aln2 = "".join(a2)
        L = len(aln1)
        if L > best_len or (L == best_len and aln1 < best_align[0]):
            best_len = L
            best_align = (aln1, aln2)

    if mode == "global" or best_align[0]:
        with open(output_path, "w") as f:
            f.write(f">{n1}\n{best_align[0]}\n>{n2}\n{best_align[1]}\n")