# -*- coding: utf-8 -*-
"""hw4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rMO4pDt2WSkZCY6tCIUthfwh_iiLCiNU
"""

def alignment(input_path, score_path, output_path, aln, gap_open, gap_extend):
    # Read FASTA
    names = []
    seqs = []
    cur = []
    with open(input_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if line.startswith(">"):
                if cur:
                    seqs.append("".join(cur))
                    cur = []
                names.append(line[1:].strip())
            else:
                cur.append(line)
    if cur:
        seqs.append("".join(cur))
    s1, s2 = seqs[0], seqs[1]
    n1, n2 = names[0], names[1] if len(names) > 1 else "seq2"

    # Substitution matrix
    lines = [l.strip() for l in open(score_path) if l.strip() and not l.lstrip().startswith("#")]
    header = lines[0].split()
    score = {a: {} for a in header}
    for row in lines[1:]:
        p = row.split()
        r = p[0]
        for j, v in enumerate(p[1:]):
            score[r][header[j]] = int(v)

    def sub(a, b):
        return score[a][b] if b in score[a] else -1

    m, n = len(s1), len(s2)
    go = -abs(int(gap_open))
    ge = -abs(int(gap_extend))
    mode = aln.lower()

    # Initialize DP matrices:
    M = [[0] * (n + 1) for _ in range(m + 1)]
    X = [[0] * (n + 1) for _ in range(m + 1)]
    Y = [[0] * (n + 1) for _ in range(m + 1)]
    T = [[None] * (n + 1) for _ in range(m + 1)]

    # Global Alignment
    if mode == "global":
        for i in range(1, m + 1):
            X[i][0] = go + (i - 1) * ge
            M[i][0] = X[i][0]
        for j in range(1, n + 1):
            Y[0][j] = go + (j - 1) * ge
            M[0][j] = Y[0][j]
        M[0][0] = 0

        # Fill DP tables
        for i in range(1, m + 1):
            for j in range(1, n + 1):
                X[i][j] = max(X[i - 1][j] + ge, M[i - 1][j] + go)
                Y[i][j] = max(Y[i][j - 1] + ge, M[i][j - 1] + go)
                M[i][j] = max(M[i - 1][j - 1], X[i - 1][j - 1], Y[i - 1][j - 1]) + sub(s1[i - 1], s2[j - 1])
                T[i][j] = max((M[i][j], "M"), (X[i][j], "X"), (Y[i][j], "Y"))[1]

        # Traceback from bottom right
        i, j = m, n
        a1, a2 = [], []
        state = "M"
        while i > 0 or j > 0:
            if state == "M":
                a1.append(s1[i - 1])
                a2.append(s2[j - 1])
                i -= 1
                j -= 1
                state = max((M[i][j], "M"), (X[i][j], "X"), (Y[i][j], "Y"))[1]
            elif state == "X":
                a1.append(s1[i - 1])
                a2.append("-")
                i -= 1
                state = "X" if X[i][j] + ge == X[i + 1][j] else "M"
            else:
                a1.append("-")
                a2.append(s2[j - 1])
                j -= 1
                state = "Y" if Y[i][j] + ge == Y[i][j + 1] else "M"

        # Output aligned sequences in FASTA format
        aln1 = "".join(reversed(a1))
        aln2 = "".join(reversed(a2))
        with open(output_path, "w") as f:
            f.write(f">{n1}\n{aln1}\n>{n2}\n{aln2}\n")

    # Local Alignment
    elif mode == "local":
        best = 0
        cells = []
        # Fill DP tables, track best-scoring cells
        for i in range(1, m + 1):
            for j in range(1, n + 1):
                X[i][j] = max(X[i - 1][j] + ge, M[i - 1][j] + go, 0)
                Y[i][j] = max(Y[i][j - 1] + ge, M[i][j - 1] + go, 0)
                M[i][j] = max(M[i - 1][j - 1], X[i - 1][j - 1], Y[i - 1][j - 1], 0) + sub(s1[i - 1], s2[j - 1])
                for val, label in [(M[i][j], "M"), (X[i][j], "X"), (Y[i][j], "Y")]:
                    if val > best:
                        best = val
                        cells = [(i, j, label)]
                    elif val == best:
                        cells.append((i, j, label))

        # Traceback for each top-scoring alignment
        results = []
        for i, j, state in cells:
            a1, a2 = [], []
            while i > 0 and j > 0:
                if state == "M" and M[i][j] == 0:
                    break
                if state == "X" and X[i][j] == 0:
                    break
                if state == "Y" and Y[i][j] == 0:
                    break
                if state == "M":
                    a1.append(s1[i - 1])
                    a2.append(s2[j - 1])
                    prev = M[i][j] - sub(s1[i - 1], s2[j - 1])
                    if M[i - 1][j - 1] == prev:
                        state = "M"
                    elif X[i - 1][j - 1] == prev:
                        state = "X"
                    else:
                        state = "Y"
                    i -= 1
                    j -= 1
                elif state == "X":
                    a1.append(s1[i - 1])
                    a2.append("-")
                    if X[i - 1][j] + ge == X[i][j]:
                        state = "X"
                    else:
                        state = "M"
                    i -= 1
                else:
                    a1.append("-")
                    a2.append(s2[j - 1])
                    if Y[i][j - 1] + ge == Y[i][j]:
                        state = "Y"
                    else:
                        state = "M"
                    j -= 1
            a1.reverse()
            a2.reverse()
            results.append(("".join(a1), "".join(a2)))

        # Select alignments with max length, break ties by lexicographical order
        if not results:
            return
        max_len = max(len(p[0]) for p in results)
        top = [p for p in results if len(p[0]) == max_len]
        top.sort()
        with open(output_path, "w") as f:
            for a1, a2 in top:
                f.write(f">{n1}\n{a1}\n>{n2}\n{a2}\n")

